root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/main ./cmd/main.go"
bin = "tmp/main"
args_bin = []
include_ext = ["go", "templ"]
exclude_dir = ["tmp", "static"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
stop_on_error = true
send_interrupt = true

[log]
silent = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
